# the content of the movie database is taken from the textbook Concrete Abstractions: An
# Introduction to Computer Science Using Scheme, by Max Hailperin, Barbara Kaiser, and
# Karl Knight, Copyright (c) 1998 by the authors. Full text is available for free at
# http://www.gustavus.edu/+max/concrete-abstractions.html

# the Scheme file, Revision 1.3 as of 2005/12/20 14:09:37, has been reformated for
# Python. The original file is available as
# http://www.gustavus.edu/academics/mcs/max/concabs/code/movie.scm

# list of tuples w/ following format (the first tuple in the list is also annotated):
# each tuple contains title, director, year and actors/actresses
# `[(title, director, year, [actress_one, actor_two, ...]), ...]`
from typing import List, Tuple

movie_db: List[Tuple[str, str, int, List[str], str]] = [
    (
        "amarcord",  # title
        "federico fellini",  # director
        1974,  # year
        [
            "magali noel",
            "bruno zanin",
            "pupella maggio",
            "armando drancia",
        ],  # actors/actresses
        "comedy/drama",
    ),
    (
        "the big easy",
        "jim mcbride",
        1987,
        [
            "dennis quaid",
            "ellen barkin",
            "ned beatty",
            "lisa jane persky",
            "john goodman",
            "charles ludlam",
        ],
        "thriller/crime",
    ),
    (
        "boyz n the hood",
        "john singleton",
        1991,
        [
            "cuba gooding jr.",
            "ice cube",
            "larry fishburne",
            "tyra ferrell",
            "morris chestnut",
        ],
        "thriller/crime",
    ),
    (
        "dead again",
        "kenneth branagh",
        1991,
        [
            "kenneth branagh",
            "emma thompson",
            "andy garcia",
            "derek jacobi",
            "hanna schygulla",
        ],
        "time killer",
    ),
    (
        "the godfather",
        "francis ford coppola",
        1972,
        ["marlon brando", "al pacino", "james caan", "robert duvall", "diane keaton"],
        "it insists upon itself",
    ),
    (
        "an american in paris",
        "vincente minnelli",
        1952,
        ["gene kelley", "leslie caron", "oscar levant", "nina foch", "george guetary"],
        "musical/romance",
    ),
    (
        "casablanca",
        "michael curtiz",
        1942,
        [
            "humphrey bogart",
            "ingrid bergman",
            "paul henreid",
            "claude rains",
            "sydney greenstreet",
            "peter lorre",
            "s z sakall",
            "conrad veidt",
            "dooley wilson",
        ],
        "romance",
    ),
    (
        "citizen kane",
        "orson welles",
        1941,
        [
            "orson welles",
            "joseph cotten",
            "dorothy comingore",
            "ray collins",
            "george coulouris",
            "agnes moorehead",
            "ruth warrick",
        ],
        "mystery"
    ),
    (
        "gone with the wind",
        "victor fleming",
        1939,
        [
            "clark gable",
            "vivien leigh",
            "leslie howard",
            "olivia de havilland",
            "hattie mcdaniel",
            "butterfly mcqueen",
        ],
        "romance/war",
    ),
    (
        "lawrence of arabia",
        "david lean",
        1962,
        [
            "peter otoole",
            "alec guinness",
            "anthony quinn",
            "jack hawkins",
            "jose ferrer",
            "omar sharif",
            "anthony quayle",
            "claude rains",
            "arthur kennedy",
            "donald wolfit",
        ],
        "war/adventure"
    ),
    (
        "the manchurian candidate",
        "john frankenheimer",
        1962,
        [
            "frank sinatra",
            "laurence harvey",
            "janet leigh",
            "angela lansbury",
            "henry silva",
            "james gregory",
            "leslie parrish",
            "john mcgiver",
            "khigh dhiegh",
            "james edwards",
        ],
        "thriller/war",
    ),
    (
        "metropolis",
        "fritz lang",
        1926,
        [
            "alfred abel",
            "gustay frohlich",
            "brigitte helm",
            "rudolf kleinrogge",
            "heinrich george",
        ],
        "scifi/thriller",
    ),
    (
        "othello",
        "orson welles",
        1952,
        [
            "orson welles",
            "michael mac liammoir",
            "robert coote",
            "suzanne cloutier",
            "faye compton",
            "doris dowling",
            "michael laurence",
        ],
        "romance"
    ),
    (
        "spartacus",
        "stanley kubrick",
        1960,
        [
            "kirk douglas",
            "laurence olivier",
            "jean simmons",
            "charles laughton",
            "peter ustinov",
            "john gavin",
            "tony curtis",
            "woody strode",
        ],
        "action"
    ),
    (
        "a star is born",
        "george cuckor",
        1954,
        [
            "judy garland",
            "james mason",
            "jack carson",
            "tommy noonan",
            "charles bickford",
        ],
        "romance/music",
    ),
    (
        "after the rehearsal",
        "ingmar bergman",
        1984,
        ["erland josephson", "ingrid thulin", "lena olin", "nadja palmstjerna-weiss"],
        "drama/comedy",
    ),
    (
        "amadeus",
        "milos forman",
        1984,
        [
            "f murray abraham",
            "tom hulce",
            "elizabeth berridge",
            "simon callow",
            "roy dotrice",
            "christine ebersole",
            "jeffrey jones",
        ],
        "musical/drama",
    ),
    (
        "blood simple",
        "joel coen",
        1985,
        [
            "john getz",
            "frances mcdormand",
            "dan hedaya",
            "m emmet walsh",
            "samm-art williams",
        ],
        "crime/thriller",
    ),
    (
        "chinatown",
        "roman polanski",
        1974,
        [
            "jack nicholson",
            "faye dunaway",
            "john huston",
            "perry lopez",
            "john hillerman",
            "darrell zwerling",
            "diane ladd",
            "roman polanski",
        ],
        "thriller/mystery",
    ),
    (
        "the cotton club",
        "francis ford coppola",
        1984,
        [
            "richard gere",
            "gregory hines",
            "diane lane",
            "lonette mckee",
            "bob hoskins",
            "james remar",
            "fred gwynne",
        ],
        "musical/crime",
    ),
    (
        "the crying game",
        "neil jordan",
        1992,
        [
            "stephen rea",
            "jaye davidson",
            "forest whitaker",
            "miranda richardson",
            "adrian dunbar",
            "breffini mckenna",
            "joe savino",
        ],
        "thriller/romance",
    ),
    (
        "the day of the jackal",
        "fred zinnemann",
        1973,
        [
            "edward fox",
            "terence alexander",
            "michel auclair",
            "alan badel",
            "tony britton",
            "denis carey",
            "olga georges-picot",
            "cyril cusack",
        ],
        "thriller",
    ),
    (
        "diva",
        "jean-jacques beineix",
        1981,
        [
            "wilhelmenia wiggins fernandez",
            "frederic andrei",
            "richard bohringer",
            "thay an luu",
            "jacques fabbri",
            "chantal deruaz",
        ],
        "thriller/crime"
    ),
    (
        "the dresser",
        "peter yates",
        1984,
        ["albert finney", "tom courtenay", "edward fox", "zena walker"],
        "drama/comedy",
    ),
    (
        "el norte",
        "gregory nava",
        1983,
        [
            "zaide silvia gutierrez",
            "david villalpando",
            "ernesto gomez cruz",
            "alicia del lago",
            "trinidad silva",
        ],
        "adventure/thriller",
    ),
    (
        "the exorcist",
        "william friedkin",
        1973,
        [
            "ellen burstyn",
            "linda blair",
            "jason miller",
            "max von sydow",
            "kitty winn",
            "lee j cobb",
        ],
        "horror/thriller",
    ),
    (
        "a fish called wanda",
        "michael chrichton",
        1988,
        [
            "john cleese",
            "jamie lee curtis",
            "kevin kline",
            "michael palin",
            "maria aitken",
            "tom georgeson",
            "patricia hayes",
        ],
        "comedy/crime",
    ),
    (
        "flirting",
        "john duigan",
        1992,
        [
            "noah taylor",
            "thandie newton",
            "nicole kidman",
            "bartholomew rose",
            "felix nobis",
            "josh picker",
            "kiri paramore",
        ],
        "romance/drama",
    ),
    ("gates of heaven", "errol morris", 1978, [], "documentary"),
    (
        "house of games",
        "david mamet",
        1987,
        [
            "lindsay crouse",
            "joe mantegna",
            "mike nussman",
            "lilia skala",
            "j t walsh",
            "jack wallace",
        ],
        "thriller/noir",
    ),
    (
        "iceman",
        "fred schepisi",
        1984,
        ["timothy hutton", "john lone", "lindsay crouse"],
        "crime/thriller",
    ),
    (
        "jaws",
        "steven spielberg",
        1975,
        [
            "roy scheider",
            "robert shaw",
            "richard dreyfuss",
            "lorraine gary",
            "murray hamilton",
        ],
        "shark/thriller/action/suspense/monster"
    ),
    (
        "johnny got his gun",
        "dalton trumbo",
        1971,
        [
            "timothy bottoms",
            "kathy fields",
            "jason robards",
            "diane varsi",
            "donald sutherland",
            "eduard franz",
        ],
        "anti-war/war",
    ),
    (
        "local hero",
        "bill forsyth",
        1983,
        [
            "burt lancaster",
            "peter reigert",
            "peter capaldi",
            "fulton mckay",
            "denis lawson",
        ],
        "comedy/drama",
    ),
    (
        "malcolm x",
        "spike lee",
        1992,
        [
            "denzel washington",
            "angela basset",
            "albert hall",
            "al freeman jr",
            "delroy lindo",
            "spike lee",
        ],
        "drama",
    ),
    (
        "top gun",
        "tony scott",
        1986,
        [
            "tom cruise",
            "val kilmer",
            "kelly mcgillis",
            "anthony edwards",
            "meg ryan",
        ],
        "action/war",
    ),
    (
        "the terminator",
        "james cameron",
        1984,
        [
            "arnold schwarzenegger",
            "linda hamilton",
            "michael biehn",
            "earl boen",
            "bill paxton",
            "lance henriksen",
        ],
        "action/war/robots/futuristic"
    ),
    (
        "jurassic park",
        "steven spielburg",
        1993,
        [
            "laura dem",
            "jeff goldblum",
            "sam neill",
            "ariana richards",
            "richard attenborough",
            "BD wong",
        ],
        "thriller/adventure/dinosaurs/monster",
    ),
     (
        "sharknado",
        "anthony c. ferrante",
        2013,
        [
            "ian ziering",
            "cassie scerbo",
            "jaason simmons",
            "adrian bustamante",
        ],
        "adventure/action/monster/natural disaster/shark",
    ),
    (
        "the shallows",
        "jaume collet-serra",
        2016,
        [
            "blake lively",
            "oscar jaenada",
            "sedona legge",
            "brett cullen",
        ],
        "thriller/action/monster/shark",
    ),
    (
        "big",
        "penny marshall",
        1988,
        [
            "tom hanks",
            "elizabeth perkins",
            "jared rushton",
            "david moscow",
            "robert loggia",
            "john heard",
        ],
        "comedy",
    ),
    (
        "the truman show",
        "peter weir",
        1998,
        [
            "jim carrey",
            "laura linney",
            "ed harris",
            "natascha mcelhone",
            "noah emmerich"
        ],
        "comedy/scifi",
    ),
    (
        "the matrix",
        "lana Wachowski, lilly Wachowski",
        1999,
        [
            "keanu reaves",
            "carrie-anne moss",
            "laurence fishborne",
            "hugo weaving",
            "gloria foster",
        ],
        "scifi/action",
    ),
    (
        "the abyss",
        "james cameron",
        1989,
        [
            "ed harris",
            "mary elizabeth mastrantonio",
            "michael biehn",
            "kidd brewer jr",
            "dick warlock",
        ],
        "scifi/adventure",
    ),
    (
        "crouching tiger, hidden dragon",
        "ang lee",
        2000,
        [
            "michelle yeoh",
            "zhang ziyi",
            "chow yun fat",
            "chang chen",
            "xian gao",
            "cheng pei-pei",
        ],
        "action/romance",
    ),
    (
        "shark exorcist",
        "donald farmer",
        2015,
        [
            "donald farmer",
            "alaine huntington",
            "bobby kerecz",
            "christy moritz",
        ],
        "shark/adventure/bad-shark-movie/monster",
    ),
    (
        "bad cgi sharks",
        "majama",
        2019,
        [
            "ben palacios",
            "jenn liu",
            "jason ellsworth",
            "matthew ellsworth",
            "matteo molinari",
            "dale e. turner",
        ],
        "shark/comedy/monster",
    ),  
    (
        "the meg",
        "jon turteltaub",
        2018,
        [
            "jason statham",
            "li bingbing",
            "ruby rose",
            "shuya sophia cai",
            "rainn wilson",
        ],
    ),
    (
        "6 headed shark attack",
        "mark atkins",
        2018,
        [
            "thandi sebe",
            "naima sebe",
            "meghan oberholzer",
            "brandon auret",
            "cord newman",
            "caitlin harty (baddie)",
        ],
    ),  
    (
        "the sandlot",
        "david mickey evans",
        1993,
        [
            "mike vitar",
            "patrick renna",
            "marty york",
            "chauncey leopardi",
            "tom guiry",
        ],
        "family/sports",
    ),
    (
        "alien",
        "ridley scott",
        1979,
        [
            "sigourney weaver",
            "tom skerritt",
            "veronica catwright",
            "john hurt",
            "ian holm",
            "harry dean stanton",
        ],
        "scifi/horror/monster/adventure",
    ),
    (
        "inception",
        "christopher nolan",
        2010,
        [
            "leonardo dicaprio",
            "cillian murphy",
            "joseph gordon-levitt",
            "tom hardy",
            "elliot page",
            "marion cotillard",
        ],
        "scifi/action",
    ),
    (
        "the sixth sense",
        "m night shyamalan",
        1999,
        [
            "haley joel osment",
            "bruce willis",
            "toni collette",
            "donnie wahlberg",
            "mischa barton",
        ],
        "horror/mystery",
    ),
    (
        "mad max: fury road",
        "george miller",
        2015,
        [
            "tom hardy",
            "charlize theron",
            "nicholas hoult",
            "hugh keays-byrne",
            "zoë kravitz",
            "courtney eaton",
        ],
        "action/scifi",
    ),
    (
        "tron",
        "steven lisburger",
        1982,
        [
            "jeff bridges",
            "bruce boxleitner",
            "david warner",
            "cindy morgan",
            "dan shor",
            "barnard hughes",
        ],
        "scifi/action",
    ),
]